name: steamturbines
channels:
    - conda-forge
    - anaconda
dependencies:
    - python=3.6.3
    - pandas=0.21.1
    - pulp=1.6.8
    - glpk=4.65
    - openpyxl=3.0.2
    - xlrd>=0.9.0
    - matplotlib=3.1.1
    - jupyter
    - pip
    - pip:
        - xlrd==1.2.0
